name: iotrafix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  google_maps_flutter: ^2.5.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cupertino_icons: ^1.0.8
  icons_plus: ^4.0.0
  google_fonts: ^6.2.1
  lottie: ^2.7.0
  vibration: ^3.1.3
  curved_navigation_bar: ^1.0.6
  http: ^1.3.0
  flutter_stripe: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/google.jpg
    - assets/images/car.jpg
    - assets/images/emptybg.jpg
    - assets/images/profile_pic.jpg
